function [channel_alias, channel_alias_ref1, channel_alias_ref2] = get_channel_alias()

channel_alias = struct('C3',{{'c3-a2','EEG C3-A2'}},...
    'C4',{{'c4-a1','EEG C4-A1'}},...
    'F3',{{'f3-a2','EEG F3-A2'}},...
    'F4',{{'f4-a1','EEG F4-A1'}},...
    'O1',{{'o1-a2','EEG O1-A2'}},...
    'O2',{{'o2-a1','EEG O2-A1'}},...
    'EOGR',{{'eogr-a1','EOGH-A1','EEG EOGH-A1','EEG EOGH-A1-Ref','E2'}},...
    'EOGL',{{'eogl-a2','EOGL-A2','EEG EOGV-A2','EEG EOGV-A2-Ref','E1'}},...
    'TIBR',{{'TIBH','TibR','EEG TIBH-Ref','tibr','EMG TIBH','TIBH-Gnd','PLMr','LMr'}},...
    'TIBL',{{'TIBV','TibL','EEG TIBV-Ref','tibl','EMG TIBV','TIBV-Gnd','PLMl','LMl'}},...
    'ECG',{{'ECG','ECG EKG','ecg','ECG II', 'ECG 2','EKG','EKG-Gnd','EMG EKG'}},...
    'CHIN',{{'CHIN','Chin','chin','EMG Chin','EMG CHIN','EMG','Chin-Gnd'}},...
    'NASALPRES',{{'Nasal','Air Nasal','Nasal-Gnd','EEG Nasal-Ref','nasal','Flow Pres','Pressure Flow','Flow Pr'}},...
    'ABD',{{'Abdomen','Resp Abdomen','RIP Abdom','Abdomen-Gnd','abdomen','RIP Abdomen','Resp/Abd','EEG Abd-Ref'}},...
    'THO',{{'Thorax','Resp Thorax','RIP Thora','Thorax-Gnd','thorax','RIP Thorax','EEG Tho-Ref'}},...
    'SaO2',{{'SpO2','SaO2 SpO2','SAO2-Gnd','SaO2 SAO2','sao2','SAO2','SPO2'}});

channel_alias_ref1 = struct('C3',{{'C3','EEG C3-Ref','C3-Ref'}},...
    'C4',{{'C4','EEG C4-Ref','C4-Ref'}},...
    'F3',{{'F3','EEG F3-Ref','F3-Ref'}},...
    'F4',{{'F4','EEG F4-Ref','F4-Ref'}},...
    'O1',{{'O1','EEG O1-Ref','O1-Ref'}},...
    'O2',{{'O2','EEG O2-Ref','O2-Ref'}},...
    'EOGR',{{'EOGH','EEG EOGH-Ref','EOGH-Ref','EOGr'}},...
    'EOGL',{{'EOGV','EEG EOGV-Ref','EOGV-Ref','EOGl'}},...
    'TIBR',{{}},...
    'TIBL',{{}},...
    'ECG',{{}},...
    'CHIN',{{'EMG2','EMG+','ChinR'}},...
    'NASALPRES',{{}},...
    'ABD',{{}},...
    'THO',{{}},...
    'SaO2',{{}});

channel_alias_ref2 = struct('C3',{{'A2','A2-Ref','EEG A2-Ref','M2'}},...
    'C4',{{'A1','A1-Ref','EEG A1-Ref','M1'}},...
    'F3',{{'A2','A2-Ref','EEG A2-Ref','M2'}},...
    'F4',{{'A1','A1-Ref','EEG A1-Ref','M1'}},...
    'O1',{{'A2','A2-Ref','EEG A2-Ref','M2'}},...
    'O2',{{'A1','A1-Ref','EEG A1-Ref','M1'}},...
    'EOGR',{{'A1','A1-Ref','EEG A1-Ref','M1'}},...
    'EOGL',{{'A2','A2-Ref','EEG A2-Ref','M2'}},...
    'TIBR',{{}},...
    'TIBL',{{}},...
    'ECG',{{}},...
    'CHIN',{{'EMG1','EMG-','ChinL'}},...
    'NASALPRES',{{}},...
    'ABD',{{}},...
    'THO',{{}},...
    'SaO2',{{}});
end